### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by Eduard123321** [mlichvar/chrony-fuzz#1]
please show some examples of test runs, I would appreciate it

**Comment by mlichvar** [comment]
The README file contains examples. Does it not work for you?

**Comment by Eduard123321** [comment]
startup error:


error: error applying changes: ntp_io.c:513
error: ntp_io.c: failed to apply patch
Error applying changes on 0009 simplify protocol checks

**Comment by mlichvar** [comment]
Ah, I see. I didn't push the updated patch for current chrony code. I'll do that shortly.

**Comment by mlichvar** [comment]
It should be fixed now. Thanks.

If you have other issues to report, please submit it on gitlab. This is just a mirror of the repository.
